//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Platform.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("ChiTietChungTuMuaDichVu")]
    public partial class ChiTietChungTuMuaDichVu
    {
        [Key]
        public int MaChiTietChungTuMuaDichVu { get; set; }
        public string MaChungTuMuaDichVu { get; set; }
        public string MaDichVu { get; set; }
        public string TKChiPhi_TKKho { get; set; }
        public string TKCongNo { get; set; }
        public string DoiTuong { get; set; }
        public string TenDoiTuong { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<double> ThanhTien { get; set; }

        public virtual ChungTuMuaDichVu ChungTuMuaDichVu { get; set; }
        public virtual DichVu DichVu { get; set; }
    }
}
