//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Platform.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("ChiTietLapRapThaoDo")]
    public partial class ChiTietLapRapThaoDo
    {
        [Key]
        public int MaChiTietLapRapThaoDo { get; set; }
        public string MaLapRapThaoDo { get; set; }
        public string MaHang { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<double> ThanhTien { get; set; }
    
        public virtual HangHoa HangHoa { get; set; }
        public virtual LapRapThaoDo LapRapThaoDo { get; set; }
    }
}
