//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Platform.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("HopDongMua")]
    public partial class HopDongMua
    {   
        [Key]
        public string MaHopDongMua { get; set; }
        public string TrichYeu { get; set; }
        public string MaNhaCungCap { get; set; }
        public Nullable<int> MaLoaiTien { get; set; }
        public Nullable<double> TyGia { get; set; }
        public string GiaTriHopDong { get; set; }
        public string NguoiLienHe { get; set; }
        public string GiaTriHopDongQuyDoi { get; set; }
        public Nullable<System.DateTime> HanGiaoHang { get; set; }
        public Nullable<int> MaTinhTrang { get; set; }
        public string DiaChiGiaoHang { get; set; }
        public string GiaTriThanhLy { get; set; }
        public string GiaTriThanhLyQuyDoi { get; set; }
        public Nullable<System.DateTime> HanThanhToan { get; set; }
        public string NgayThanhLy_HuyBo { get; set; }
        public string MaSoNhanVien { get; set; }
        public string LyDo { get; set; }
        public string DieuKhoanKhac { get; set; }
        public Nullable<bool> LaHopDongPhatSinh { get; set; }
        public Nullable<double> TienChietKhau { get; set; }
        public Nullable<double> TienThueGTGT { get; set; }
        public Nullable<double> TongTienThanhToan { get; set; }
        public Nullable<System.DateTime> NgayKy { get; set; }


        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietHopDongMua> ChiTietHopDongMuas { get; set; }
        public virtual LoaiTien LoaiTien { get; set; }
        public virtual NhaCungCap NhaCungCap { get; set; }
        public virtual NhanVien NhanVien { get; set; }
        public virtual TinhTrang TinhTrang { get; set; }
    }
}
