//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Platform.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("LapRapThaoDo")]
    public partial class LapRapThaoDo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LapRapThaoDo()
        {
            this.ChiTietLapRapThaoDoes = new HashSet<ChiTietLapRapThaoDo>();
        }
        [Key]
        public string MaLapRapThaoDo { get; set; }
        public string MaHang { get; set; }
        public string MaThanhPham { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<System.DateTime> Ngay { get; set; }
        public string DienGiai { get; set; }
        public Nullable<double> DonGia { get; set; }
        public Nullable<double> ThanhTien { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietLapRapThaoDo> ChiTietLapRapThaoDoes { get; set; }
        public virtual HangHoa HangHoa { get; set; }
        public virtual ThanhPham ThanhPham { get; set; }
    }
}
