//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Platform.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("LenhSanXuat")]
    public partial class LenhSanXuat
    {
        
        [Key]
        public string MaLenhSanXuat { get; set; }
        public string DienGiai { get; set; }
        public Nullable<System.DateTime> Ngay { get; set; }
        public Nullable<int> MaTinhTrang { get; set; }
        public Nullable<bool> DaGhiSo { get; set; }


        public virtual ICollection<LenhSanXuat_NVL> LenhSanXuat_NVL { get; set; }
      
        public virtual ICollection<LenhSanXuat_ThanhPham> LenhSanXuat_ThanhPham { get; set; }
        public virtual TinhTrang TinhTrang { get; set; }
    }
}
