//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Platform.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("LoaiChi")]
    public partial class LoaiChi
    {
        [Key]
        public int MaLoaiChi { get; set; }
        public string TenLoaiChi { get; set; }
        public string GhiChu { get; set; }
    
        public virtual ICollection<PhieuChi> PhieuChis { get; set; }
    }
}
