//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Platform.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("PhieuThu")]
    public partial class PhieuThu
    {   
        [Key]
        public string MaPhieuThu { get; set; }
        public string MaKhachHang { get; set; }
        public string MaSoNhanVien { get; set; }
        public Nullable<int> MaLoaiThu { get; set; }
        public Nullable<int> MaTinhTrang { get; set; }
        public string LyDoNop { get; set; }
        public string DienGiai { get; set; }
        public Nullable<System.DateTime> NgayHoachToan { get; set; }
        public DateTime  NgayChungTu { get; set; }
        public Nullable<double> TongTienHang { get; set; }
        public Nullable<double> TienChietKhau { get; set; }
        public Nullable<double> TienThueGTGT { get; set; }
        public Nullable<double> TongTienThanhToan { get; set; }
        public Nullable<bool> DaGhiSo { get; set; }
        public Nullable<int> ChungTuGoc { get; set; }
        public Nullable<int> MaLoaiTien { get; set; }
        public Nullable<double> TyGia { get; set; }
        public string ChungTuThamChieu { get; set; }
        public string NguoiNop { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietThu> ChiTietThus { get; set; }
        public virtual KhachHang KhachHang { get; set; }
        public virtual LoaiThu LoaiThu { get; set; }
        public virtual NhanVien NhanVien { get; set; }
        public virtual TinhTrang TinhTrang { get; set; }
        public virtual LoaiTien LoaiTien { get; set; }

    }
}
