//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Platform.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("TaiKhoanNganHang")]
    public partial class TaiKhoanNganHang
    {
       
        [Key]
        public string MaTaiKhoan { get; set; }
        public string TenNganHang { get; set; }
        public string ChiNhanh { get; set; }
        public string TinhTP { get; set; }
    
        public virtual ICollection<KhachHang_TaiKhoan> KhachHang_TaiKhoan { get; set; }
        public virtual ICollection<NhaCungCap_TaiKhoan> NhaCungCap_TaiKhoan { get; set; }
    }
}
