//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Platform.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("ChiTietPhieuThu")]
    public partial class ChiTietThu
    {
        [Key]
        public int MaCTPT { get; set; }
        public string MaPhieuThu { get; set; }
        public string MaHang { get; set; }
        public int SoLuong { get; set; }
        public Nullable<double> SoTien { get; set; }
        public string DienGiai { get; set; }
        public string SoTaiKhoanCo { get; set; }
        public string SoTaiKhoanNo { get; set; }
        public string MaKhachHang { get; set; }
        public string TenKhachHang { get; set; }
        public string TaiKhoanNganHang { get; set; }
        public string MucThuChi { get; set; }
        public string DonVi { get; set; }
        public string CongTrinh { get; set; }
        public string HopDongBan { get; set; }
        public string MaThongKe { get; set; }
        public virtual HangHoa HangHoa { get; set; }
        public virtual PhieuThu PhieuThu { get; set; }
    }
}
