//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Platform.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("ChiTietGiamGiaHangMua")]
    public partial class ChiTietGiamGiaHangMua
    {
        [Key]
        public int MaChiTietGiamGiaHangMua { get; set; }
        public string MaGiamGiaHangMua { get; set; }
        public string MaHang { get; set; }
        public string Kho { get; set; }
        public string TKKho { get; set; }
        public string TKCongNo { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<double> ThanhTien { get; set; }
        public string DienGiaiThue { get; set; }
        public Nullable<double> TienThueGTGT { get; set; }
        public string TKThueGTGT { get; set; }
        public string NhomHHDVMuaVao { get; set; }
        public string SoLo { get; set; }
        public string SoCTMuaHang { get; set; }
        public string SoHDMuaHang { get; set; }
        public string NgayHDMuaHang { get; set; }
        public string MaHopDongMua { get; set; }
        public string MaThongKe { get; set; }

        public virtual GiamGiaHangMua GiamGiaHangMua { get; set; }
        public virtual HopDongMua HopDongMua { get; set; }
    }
}
