//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Platform.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("CoSo")]
    public partial class CoSo
    {
     
   
          [Key]
        public string MaCoSo { get; set; }
        public string DiaChi { get; set; }
        public string TenCoSo { get; set; }
        public string CapToChuc { get; set; }
    
     
        public virtual ICollection<TaiSan> TaiSans { get; set; }
    }
}
