//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Platform.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("LoaiTien")]
    public partial class LoaiTien
    {
        
        [Key]
        public int MaLoaiTien { get; set; }
        public string TenLoaiTien { get; set; }
        public string VietTat { get; set; }
        public string MenhGia { get; set; }
        public Nullable<double> TyGia_VND { get; set; }
    
        public virtual ICollection<PhieuThu> PhieuThus { get; set; }
    }
}
