//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Platform.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("NgonNgu")]
    public partial class NgonNgu
    {
        [Key]
        public long ID { get; set; }
        public string MaSoNhanVien { get; set; }

        public string TenNgonNgu { get; set; }
        public string Nghe { get; set; }
        public string Noi { get; set; }
        public string Doc { get; set; }
        public string Viet { get; set; }
    
        public virtual NhanVien NhanVien { get; set; }
    }
}
