//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Platform.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("NhanVien")]
    public partial class NhanVien
    {


       [Key]
        public string MaSoNhanVien { get; set; }
        public string HoVaTen { get; set; }
        public string GioiTinh { get; set; }
        public string SoCMND { get; set; }
        public System.DateTime NgayCapCMND { get; set; }
        public string NoiCapCMND { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
        public string TinhTrangHonNhan { get; set; }
        public string QuocTich { get; set; }
        public string DiaChi { get; set; }
        public string SoDienThoai { get; set; }
        public string Email { get; set; }
        public string HoTenLienHeKhanCap { get; set; }
        public string QuanHeLienHeKhanCap { get; set; }
        public string DiaChiLienHeKhanCap { get; set; }
        public string SDTLienHeKhanCap { get; set; }
        public string Hinh { get; set; }
        public int Bac { get; set; }
        public string TrangThai { get; set; }
        public string MaCoSo { get; set; }
        public string MaChucVu { get; set; }
        public string MaSoThue { get; set; }
        public string SoTaiKhoanNganHang { get; set; }
        public string TenNganHang { get; set; }
        public string ChiNhanh { get; set; }

        public virtual ICollection<HoanThanhCongViec> HoanThanhCongViecs { get; set; }
       
        public virtual ICollection<LichSuLamViec> LichSuLamViecs { get; set; }
    
        public virtual ICollection<NgonNgu> NgonNgus { get; set; }

        public virtual ICollection<QuanLyCongTac> QuanLyCongTacs { get; set; }
     
        public virtual ICollection<QuanLyNgayNghi> QuanLyNgayNghis { get; set; }
      
        public virtual ICollection<QuanLyQuaGio> QuanLyQuaGios { get; set; }
     
        public virtual ICollection<QuanLyVangMat> QuanLyVangMats { get; set; }
      
        public virtual ICollection<QuaTrinhDaoTao> QuaTrinhDaoTaos { get; set; }
     
        public virtual ICollection<The> Thes { get; set; }
      
        public virtual ICollection<ThongTinTuyenDung> ThongTinTuyenDungs { get; set; }
    }
}
