//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Platform.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("TaiKhoanKetChuyen")]
    public partial class TaiKhoanKetChuyen
    {
        [Key]
        public int Id { get; set; }
        public Nullable<int> ThuTuKetChuyen { get; set; }
        public string MaKetChuyen { get; set; }
        public string KetChuyenTu { get; set; }
        public string KetChuyenDen { get; set; }
        public string BenKetChuyen { get; set; }
        public string DienGiai { get; set; }
        public string LoaiKetChuyen { get; set; }
        public Nullable<bool> NgungTheoDoi { get; set; }
    }
}
