//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Platform.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("ThanhPham")]
    public partial class ThanhPham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ThanhPham()
        {
            this.LenhSanXuat_ThanhPham = new HashSet<LenhSanXuat_ThanhPham>();
        }
        [Key]
        public string MaThanhPham { get; set; }
        public string TenThanhPham { get; set; }
        public string DonViTinh { get; set; }
        public string HopDongBan { get; set; }
        public string DoiTuongDHCP { get; set; }
        public string MaThongKe { get; set; }
        public string DonDatHang { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LenhSanXuat_ThanhPham> LenhSanXuat_ThanhPham { get; set; }
    }
}
